Task: Lesson1
ilya-xbsoftware/webix-start pull request #1
Opened 2021-04-07 17:29 UTC by ilya-xbsoftware

- Created Layout with 3 rows;
- Used Label and Button in the 1st row;
- Added List, Datatable and Form;

2021-04-07 21:09 UTC, ekosiy commented
@ilya-xbsoftware 
Show a popup on “Profile” button click. It should be located near the button and contain a List with the following data: [ "Settings", "Log out"]
я не вижу выполнения этого пункта в проекте

2021-04-07 21:21 UTC, ekosiy commented
кнопка add view отличается по стилю
https://docs.webix.com/desktop__button.html
посмотри плз на этом примере как можно поправить стили

2021-04-07 21:29 UTC, ekosiy commented
https://docs.webix.com/desktop__list_css.html
для листа слева стили тоже не плохо было бы поправить
+ с цветом для connected не попал

2021-04-07 21:43 UTC, ekosiy reviewed
С большего весьма не плохо
я бы посоветовал улучшить несколько моментов и будет аппрув с моей стороны

2021-04-07 21:43 UTC, ekosiy commented on debug.log
> +[1202/073003.592:ERROR:directory_reader_win.cc(43)] FindFirstFile: ������� �� ������� ����� ��������� ����. (0x3)
добавь пожалуйста debug.log в gitignore

2021-04-07 21:43 UTC, ekosiy commented on src/js/app/app.js
> +import { header } from '../components/header/header';
содержимое этого файла логичнее бы смотрелось в src/js/index.js
там идет просто вызов этого файла, зачем плодить лишние сущности? Или для этого есть какая-то определенная задача?

2021-04-07 21:43 UTC, ekosiy commented on src/js/components/main/form/form.js
> +  autoHeight: true,
https://docs.webix.com/api__ui.form_autoheight_config.html
autoHeight -> autoheight
с именами свойств лучше придерживаться документации во избежание трудноуловимых багов

2021-04-08 05:10 UTC, ilya-xbsoftware commented on src/js/app/app.js
> +import { header } from '../components/header/header';
Я предполагаю, что в дальнейшем надо будет с header работать. Поэтому и вывел отдельно в файл.

2021-04-08 06:18 UTC, ekosiy commented on src/js/app/app.js
> +import { header } from '../components/header/header';
@ilya-xbsoftware в этом плане ты все абсолютно правильно делаешь - разбиваешь на абстракции для лучшего переиспользования!
вопрос в другом
у тебя есть файл src/js/index.js который вызывает app.js файл и всё. Тут у меня вопрос - что изменится, если мы сразу в src/js/index.js вставим полностью содержимое этого файла.

Это не критичное изменение и мне ок, если этого не сделать.

2021-04-08 06:36 UTC, ekosiy approved these changes

2021-04-08 07:02 UTC, Zwillinge requested changes

2021-04-08 07:02 UTC, Zwillinge commented on src/js/components/header/header.js
> +  id: 'header',
не стоит задавать id компонентам, если мы потом к ним не обращаемся. id должны быть уникальны и задавая их кому не нужно, рискуем быстро запутаться

2021-04-08 07:02 UTC, Zwillinge commented on src/js/components/main/dataTable/dataTable.js
> +  css: 'dataTable',
такой класс не описан в css, вороятно и здесь лишний

2021-04-08 07:02 UTC, Zwillinge commented on src/js/components/main/form/form.js
> +    { template: 'EDIT FILMS', type: 'section' },
темплейт типа section сам переводит буквы в uppercase

2021-04-08 07:02 UTC, Zwillinge commented on src/js/components/main/form/form.js
> +    { view: 'text', name: 'rating', label: 'Date', type:'date' },
нам на этом этапе не нужны name, лучше убрать. тем более у тебя 2 поля в одинаковым name, что в будушем приведем к ошибке. 
также не стоит задавать type:"date" текстовому полю, для этого в webix есть спец. контрол. но забегая вперед, скажу, что и он здесь не нужен, потому что редактировать придется только год, а не всю дату

2021-04-08 07:02 UTC, Zwillinge commented on src/js/components/main/sideBar/side.js
> +      type: 'clear',
нет такого типа у list. вообще ни у кого в webix нет)

2021-04-08 07:02 UTC, Zwillinge commented on src/js/components/main/sideBar/side.js
> +      view: 'button',
кнопку здесь создавать неправильно, т.к. она содержит hover стили, которые намекают на ее интерактивность 
нужна простая плашка, реализуемая через template или label

2021-04-08 08:22 UTC, ilya-xbsoftware commented on src/js/components/main/sideBar/side.js
> +      view: 'button',
доработал

2021-04-08 08:42 UTC, Zwillinge approved these changes

2021-04-08 10:19 UTC, merged