Lesson 2 completed
ilya-xbsoftware/webix-start pull request #2
Opened 2021-04-08 17:14 UTC by ilya-xbsoftware

1. Show a popup on “Profile” button click:
![Screenshot_4](https://user-images.githubusercontent.com/82055260/114066865-d923e980-98a4-11eb-8bf4-37f773a6cdf6.jpg)
2. Let users add new films to the datatable:
![Screenshot_5](https://user-images.githubusercontent.com/82055260/114067218-3c158080-98a5-11eb-8b1e-7c425ebdc1b0.jpg)
3.  Add validate rules: 
![Screenshot_6](https://user-images.githubusercontent.com/82055260/114067408-767f1d80-98a5-11eb-822c-014d420e92a3.jpg)
4. Add successful / warning  message:
![Screenshot_7](https://user-images.githubusercontent.com/82055260/114067774-daa1e180-98a5-11eb-9924-6640fa43913c.jpg)
5. Don’t add form data to the datatable if some  field doesn't comply to the rules:
![Screenshot_8](https://user-images.githubusercontent.com/82055260/114068272-6a479000-98a6-11eb-9f55-5665ee0b1906.jpg)
6.  Get user confirmation before clearing:
![Screenshot_9](https://user-images.githubusercontent.com/82055260/114068435-96631100-98a6-11eb-972d-fa820d5384be.jpg)

2021-04-08 20:08 UTC, ekosiy commented on src/js/components/main/dataTable/dataTable.js
> +  id: "filmsTable",
скорее рекомендация чем актуальная штука - постарайся везде использовать либо одинарные либо двойные кавычки, для того чтобы всё было в одном стиле. Можно в линтере прописать, если захочешь

2021-04-08 20:08 UTC, ekosiy commented on src/js/components/main/popup/popup.js
> +}).hide();
нужно ли тут делать hide? 
по идее оно по умолчанию не показывается, пока ты ему не прикажешь

2021-04-09 04:40 UTC, ilya-xbsoftware commented on src/js/components/main/dataTable/dataTable.js
> +  id: "filmsTable",
Исправил на двойные. 
В ESLint правило вписал, еще на прошлом коммите. Странно, что правило не применилось...

2021-04-09 05:50 UTC, ekosiy approved these changes

2021-04-09 08:33 UTC, Zwillinge requested changes

2021-04-09 08:33 UTC, Zwillinge commented on src/scss/main.scss
> +  color: rgb(7, 165, 7);
у message есть встроенный тип success, чтобы оно было зеленое
таким css ты делаешь все сообщеньки зелеными (даже белые которые по дефолту), это может помешать если в другом месте на проекте нужны именно белые

в конфиге сообщения у тебя css:"validTrueText" - видимо это была попытка покрасить, но она не удалась, т.к. этот класс не используется

2021-04-09 08:39 UTC, ilya-xbsoftware commented on src/scss/main.scss
> +  color: rgb(7, 165, 7);
Разобрался ! 
Все исправил.

2021-04-09 08:43 UTC, Zwillinge approved these changes

2021-04-09 08:44 UTC, merged